### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by mmathys**
Fixed path

### CODE REVIEW

**Comment by mmathys** [comment]
not quite sure though whether this is correct, if the out folder is meant to be the dist folder

**Comment by JamesMGreene** [comment]
You are correct.

**Comment by mmathys** [comment]
Owner has abandoned this project :(

**Comment by JamesMGreene** [comment]
I know. 😢 

There are multiple more active forks of it now, including [nedb-core](https://github.com/nedbhq/nedb-core) and [my own] [NestDB](https://github.com/JamesMGreene/nestdb). That's part of why I'm reviewing a lot of the open PRs and issues here to see what should be carried over. :+1:

**Comment by marcusjwhelan** [comment]
@JamesMGreene Some of us made our own but changed many things and ported over the binary tree as well to work with our system. [tedb](https://www.npmjs.com/package/tedb). I looked over a lot of the issues and tried to address them. 

If you would like to take a look or make pull requests that would be good news to have more people involved. Right now I have just got it to what I would call stable. I am waiting for issues.

**Pull request closed without merging**
