### PR TITLE
notes for dropping database

### PR DESCRIPTION
**Pull request by b1rdex**
ty @szwacz and #84

### CODE REVIEW

**Comment by RickCarlino** [comment]
I know this is somewhat late, but I would like to mention that I was looking for this in the README and only found it after some investigation.

**Comment by b1rdex** [comment]
@RickCarlino @louischatriot time to provide api for this?

**Comment by RickCarlino** [comment]
My intention was to say that it might be "general" enough to put into the README. I figured that sort of use case would be in there, and was only able to find it after searching. As for changing the API, I'm not sure. I haven't been using nedb long enough to say.

Side note: great project!

**Comment by louischatriot** [comment]
Hmm I can put it as an example in the readme but to be honest I really find that very specific. I'll update the readme.

**Comment by b1rdex** [comment]
As far as nedb is "mongodb analog" it'd be good to have same api. Mongo has
method to drop dB.

**Comment by louischatriot** [comment]
Nedb is not mongodb analog, it's almost 100% upwards compatible. The goal is not to create a JS mongo but to create a JS database that most people already know how to use, but trying to achieve feature parity with mongodb is not a good idea.

**Pull request closed without merging**
