### PR TITLE
Bump mkdirp to fix --use-strict error. Fixes #172.

### LINKED ISSUE #172: Error on mkdir with --strict mode
node_modules/nedb/node_modules/mkdirp/index.js:9
        mode = 0777 & (~process.umask());

SyntaxError: Octal literals are not allowed in strict mode.

### PR DESCRIPTION
**Pull request by jedahan**
I ran the tests before and after, both had 1 out of 271 fail.

### CODE REVIEW

**Comment by louischatriot** [comment]
Thanks for the fix, merged. Strange that you get 1 test fail, which one is it ?

**Comment by jedahan** [comment]
```shell
~/code/nedb master
❯ mocha --reporter spec --timeout 10000 --grep 'modifier is used with a non-object argument'
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.


  Model
    Modifying documents
      1) Throw an error if a modifier is used with a non-object argument


  ✖ 1 of 1 test failed:

  1) Model Modifying documents Throw an error if a modifier is used with a non-object argument:
     AssertionError: expected [Function] to throw an error
```

**Comment by louischatriot** [comment]
Which version of node or io.js are you using?

**Comment by jedahan** [comment]
node v4.0.0

**Comment by louischatriot** [comment]
Good catch, I was still on v0.10.2 and v4 brings ES6 which changed rules for Object.keys. I updated nedb to work ith ES6. Note that it worked perfectly before for code that followed the documentation, only a few edge cases wree not supported.

**Comment by jedahan** [comment]
thanks for looking into it and communicating what the changes were and why! I really appreciate the project...

**Pull request merged**
