### PR TITLE
Implement $elemMatch query operator, projection on embedded Documents and arrays, also with positional operator $, update operators $min, $max, $(positional), aggregation (see comments)

### PR DESCRIPTION
**Pull request by mitsos1os**
With this merge we can use now use projection correctly on embedded documents and document arrays using the MongoDB "Dot Notation".
Also the positional $ operator was implemented (although basic usage), to mimic mongodb behavior when used in a projection document

### CODE REVIEW

**Comment by mitsos1os** [comment]
Also added $min $max update operators, update positional operator ($) along with their tests...
Please review and comment or merge, since it is quite critical missing functionality.
Thank you for your time!

**Comment by lukasbestle** [comment]
If you need it for your project right now, consider using your fork directly. You can use Git as the source for npm.

**Comment by mitsos1os** [comment]
@lukasbestle thank you for your hint... Will do that!

**Comment by mitsos1os** [comment]
I have also created a branch in my fork for basic aggregation support.
(You can take a look at the compare here https://github.com/louischatriot/nedb/compare/master...mitsos1os:aggregation )

This includes quite some of the aggregate functionality with things missing, but the structure is easily expanded for added functionality through contribution.
More specific:
- Functionality implemented
* **$match** operator through the usage of existing functionality in *lib/model.js* **match** function
* **$unwind** operator support
* **$sort** operator through the usage of **sort** function in *lib/cursor.js*
* **$skip** operator
* **$limit** operator
* **$group** operator *(limited functionality, see below)*
* **$project** operator *(limited functionality, see below)* 

 - Things **Not** implemented
* in **$group** aggregator only support for **$sum** accumulator with integer values has been implemented.
* in **$project** operator when using *Expressions* for assigned values to new doc fields, only inclusion of existing document properties prefixed with **$** is supported

It has no conflicts with the exisitng master branch of yours and my pull request, but I haven't merged it in case @louischatriot or anyone else had any comments or suggestions.

I hope it will provide some help to everybody!
Thanks!

**Comment by mitsos1os** [comment]
I had some restructures implemented on aggregation branch, So I finally merged it to master since there was no time in making the changes both to master and aggregation branch... Feel free to comment your opinion

**Comment by louischatriot** [comment]
(copy of the email thread)

Hello,

Yeah it took me a long time to answer sorry. To be honest, your PR was the one that made me realize that I needed to add some rules about submitting PRs :) Unfortunately it would be extremely hard for me to review this PR as I need to allocate a continuous chunk of time to it and given its size I simply can't find one big enough.

That said it would be great to include this functionality and have NeDB benefit to all the work you put into this. To do so I'll need to ask you to resubmit feature by feature, this time following the PR style guide. I suggest that you start with a PR on the `$elemMatch` operator, this should be the smallest and I'll provide -hopefully- helpful feedback for subsequent (and larger) PRs. Then we can take care of the features in order from smallest to biggest: $min/$max, positional projection, aggregation with only one aggregator/accumulator, and finally rest of the aggregators accumulators.

Please make sure to follow the style guide in particular, that makes PRs a lot easier to review. For example I use comments of with three spaces before `//` and one after, starting with a capital letter, while there is no space before or after `//` in yours and the comment starts with an uncapitalized letter.

Also keep in mind the general mindset of NeDB: it is not a JS copy of MongoDB, but a JS database to be used on small or self containing projects (desktop/mobile/browser). The API compatibility is here because most people are used to MongoDB's syntax so it's easy to learn but NeDB is not a replacement for MongoDB, which is why it's sometimes a good idea to shoot for simplicity over completeness.

I'll post this on the Github PR so that everyone can benefit from the discussion, let's take it there. I'll close this PR while waiting for the next ones.

Cheers,
Louis

**Pull request closed without merging**
