### PR TITLE
Add callback to compactDatafile

### PR DESCRIPTION
**Pull request by jboulhous**
I am using nedb in a nwjs app, and i would like to compactDatafile manualy and then make a backup somewhere.

### CODE REVIEW

**Comment by lukasbestle** [comment]
+1!

I think it's important to be able to know when NeDB has completed compacting the DB. Adding this optional callback won't break anything.

**Comment by jboulhous** [comment]
Hello,
may be we could emit an event on some eventemitter.
please consider providing a way to know when compaction is done.
regards,
Jamal

**Comment by lukasbestle** [comment]
I have created a fork of NeDB in the meantime, [NewDB](https://github.com/lukasbestle/newdb), the Node Embedded Whizzy Database. It is currently based on NeDB 1.3.0 and adds this feature, both for one-time and auto-compaction.

I still think this should be part of NeDB, but until it is an official feature, you can use my fork.

To @louischatriot: My fork will continue to integrate new NeDB features and fixes and will stay fully compatible with only additional features. I really like NeDB and don't plan to generate anything selfish out of my fork, so consider it to be an alternative version of NeDB. :)

**Comment by JamesMGreene** [comment]
:+1:

**Comment by louischatriot** [comment]
As of v1.6.2, datastores fire an `compaction.done` event whenever a compaction operation is completed.

**Comment by roccomuso** [comment]
How do we catch this <code>compaction.done</code> event?

**Comment by louischatriot** [comment]
Standard event emitter on the Nedb instance, so `nedb.on('compaction.done');`

**Pull request closed without merging**
