### PR TITLE
Return modified document when updating with upsert set to false or undefined

### PR DESCRIPTION
**Pull request by dclaze**

### CODE REVIEW

**Comment by klepthys** [comment]
A way to have an array of modified docs would be much appreciated for me.

In fact I can work on this if someone can confirm it wouldn't be a problem to have newdoc being defined when no *new* document was created.

**Comment by unformatt** [comment]
+1

**Comment by JamesMGreene** [comment]
:+1: but only if it returns multiple modified documents when relevant.

**Comment by louischatriot** [comment]
The proposed implementation doesn't work, it only returns the last modified document if there are multiple updates. I created the feature though, will be part of v1.6.0 to be published today

**Pull request closed without merging**
